# The command log.
#
# Adapted from OITOOLS' src/gui/commandlog.jl. Every action that changes the session appends
# the equivalent ROTIR call here, as text. Two things follow, and they are why the log exists
# rather than being a nicety:
#
#   1. GUI work becomes publishable. "Export script" writes a runnable .jl that reproduces the
#      session, so a surface map made by clicking can be regenerated, diffed and cited.
#   2. It constrains the GUI. If an action cannot be written as a ROTIR call, the GUI has grown
#      private logic that scripts cannot reproduce — and the export test catches it.
#
# View state (camera angle, colour range, which tab is open) is deliberately NOT logged:
# replaying it changes no result, and it would bury the calls that do.

"""
    LogEntry(code; note = "", binding = "")

One replayable step. `code` is Julia source exactly as it would be typed; `note` is the
human-readable label shown in the log panel; `binding` names the variable the step assigns to,
so later steps can refer to it (`data1`, `model2`, `map1`).
"""
struct LogEntry
    code::String
    note::String
    binding::String
end
LogEntry(code::AbstractString; note::AbstractString = "", binding::AbstractString = "") =
    LogEntry(String(code), String(note), String(binding))

Base.show(io::IO, e::LogEntry) =
    print(io, isempty(e.note) ? e.code : "# " * e.note * "\n" * e.code)

"""
    log!(session, code; note = "", binding = "") -> String

Append a step and return `binding`, so callers can write `name = log!(...)`.
"""
function log!(s, code::AbstractString; note::AbstractString = "",
              binding::AbstractString = "")
    push!(s.log, LogEntry(code; note = note, binding = binding))
    return binding
end

"""
    export_script(session; header = true) -> String
    export_script(session, path; header = true) -> path

Render the command log as a runnable Julia script.

The result is what the GUI did, in order, and running it must reproduce the session. That
round trip is the strongest test available here, because any divergence means the GUI has
private logic.

The header names CairoMakie rather than GLMakie: an exported script is normally re-run
headless to regenerate a figure, and CairoMakie needs no display. Both back-ends provide the
same `*_makie` functions, so swapping the line is all it takes to get a window back.
"""
function export_script(s; header::Bool = true)
    io = IOBuffer()
    if header
        println(io, "# Generated by ROTIRGUI — reproduces this session.")
        println(io, "using ROTIR, CairoMakie")
        println(io)
    end
    for e in s.log
        isempty(e.note) || println(io, "# ", e.note)
        println(io, e.code)
        println(io)
    end
    return String(take!(io))
end

function export_script(s, path::AbstractString; header::Bool = true)
    open(path, "w") do io
        write(io, export_script(s; header = header))
    end
    return path
end

"""
    _literal(x) -> String

Render a value as Julia source. Log lines must survive a round trip, so this is exact rather
than pretty: strings are escaped and quoted, floats keep full precision.

`Symbol` keys are rendered as identifiers when they are valid ones and quoted otherwise, which
is what makes the Unicode orbital elements (`Ω`, `ω`, `dω`) come out as themselves — they are
valid Julia identifiers, and an exported script that spelled them any other way would not run.
"""
_literal(x::AbstractString) = repr(String(x))
_literal(x::Symbol)         = ":" * String(x)
_literal(x::Bool)           = x ? "true" : "false"
_literal(x::Integer)        = string(x)
_literal(x::AbstractFloat)  = repr(x)          # full round-trip precision
_literal(x::Nothing)        = "nothing"
_literal(x::AbstractVector) = "[" * join(_literal.(x), ", ") * "]"
_literal(x::Tuple)          = "(" * join(_literal.(x), ", ") * ")"
function _literal(x::AbstractDict)
    isempty(x) && return "Dict()"
    inner = join(("$(_literal(k)) => $(_literal(v))"
                  for (k, v) in sort(collect(x), by = first)), ", ")
    return "Dict(" * inner * ")"
end
_literal(x) = string(x)

"""
    _namedtuple_literal(nt) -> String

A NamedTuple as source, e.g. `(surface_type = 3, rpole = 0.5, Ω = 309.938)`.

Written out rather than `repr`'d because a `star_params` is the thing a reader of the exported
script most wants to edit, and `repr` of a NamedTuple with 20 fields is one unbroken line.
"""
function _namedtuple_literal(nt::NamedTuple; indent::AbstractString = "    ")
    isempty(nt) && return "NamedTuple()"
    parts = ["$(k) = $(_literal(v))" for (k, v) in pairs(nt)]
    return "(\n" * indent * join(parts, ",\n" * indent) * ")"
end
